language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $Ku36wga1F9_D6rfvYejQGw
  keep-history: true
  on:
    branch: Deploed